[workspace]
members = [
    "canisters/urbit-identity",
]
resolver = "2"

[workspace.dependencies]
ic-cdk = "0.19.0-beta.3"
ic-cdk-macros = "0.19.0-beta.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
